From: YOKOTA Hiroshi <yokota.hgml@gmail.com>
Date: Fri, 26 May 2023 21:27:24 +0900
Subject: Revert "Get creating outlines working again"

Forwarded: not-needed

This reverts commit 541c1d20365cdb730d809607c2b57db92c2fab25.
---
 src/calibre/utils/podofo/outlines.cpp | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/src/calibre/utils/podofo/outlines.cpp b/src/calibre/utils/podofo/outlines.cpp
index 4f80d25..c8ef099 100644
--- a/src/calibre/utils/podofo/outlines.cpp
+++ b/src/calibre/utils/podofo/outlines.cpp
@@ -24,8 +24,9 @@ create_outline(PDFDoc *self, PyObject *args) {
 
     try {
         PdfString title = podofo_convert_pystring(title_buf);
-        PdfOutlines &outlines = self->doc->GetOrCreateOutlines();
-        ans->item = outlines.CreateRoot(title);
+        PdfOutlines *outlines = self->doc->GetOutlines();
+        if (outlines == NULL) {PyErr_NoMemory(); return NULL;}
+        ans->item = outlines->CreateRoot(title);
         if (ans->item == NULL) {PyErr_NoMemory(); return NULL;}
         ans->doc = self->doc;
         auto page = get_page(self->doc, pagenum -1);
