From 24da79da0b4f108afa81e1db26b70324700ca2f8 Mon Sep 17 00:00:00 2001
From: Kovid Goyal <kovid@kovidgoyal.net>
Date: Sat, 4 Apr 2020 15:02:14 +0530
Subject: [PATCH 105/284] Missed one instance of ispy3

---
 src/calibre/devices/mtp/unix/driver.py | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

diff --git a/src/calibre/devices/mtp/unix/driver.py b/src/calibre/devices/mtp/unix/driver.py
index 7c8d8a365d..ad882f6fa5 100644
--- a/src/calibre/devices/mtp/unix/driver.py
+++ b/src/calibre/devices/mtp/unix/driver.py
@@ -371,11 +371,10 @@ class MTP_DEVICE(MTPDeviceBase):
         e = parent.folder_named(name)
         if e is not None:
             return e
-        ename = name if ispy3 else as_bytes(name)
         sid, pid = parent.storage_id, parent.object_id
         if pid == sid:
             pid = 0
-        ans, errs = self.dev.create_folder(sid, pid, ename)
+        ans, errs = self.dev.create_folder(sid, pid, name)
         if ans is None:
             raise DeviceError(
                     'Failed to create folder named %s in %s with error: %s'%
-- 
2.28.0

